### ISSUE TITLE
DB Schema spitballing

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#10]
Some super useful features that actual justify having a db:

1. Allow user to "Favourite" Validators
2. Allow Validators to have something like an "About" page, describing and selling their case on why Nominators should nominate them.
3. Make some personalisation for a particular public key, so we can save whether a key is a stash or controller, users can opt to "Level Up" their profile by connecting their social accounts and emails, then this will allow us to build up a mailing list.
4. Forum type of thing for discussing an upcoming session, grievances from the previous session, etc.

**Comment by yjkimjunior** [comment]
ok well while we were chattering Jaco went and implemented it, albeit with local storage https://github.com/polkadot-js/apps/pull/1873/files

**Comment by amaurymartiny** [comment]
I think overall we should have 2 DBs (or one DB where these two parts are clearly distinct):

DB 1: the "chain" DB. This is just given an archive node, puts all relevant information into a DB. cf https://github.com/paritytech/substrate-archive. From our backend's perspective, this DB should be **read-only**.

DB 2: the "app" DB. This DB is specific to our app, where the above points 1,2,4 would go. This DB is **read&write**.

**Comment by yjkimjunior** [comment]
roughly and minimally, 

### Chain DB
```
Table(Staking) {
  id: Int,
  Foreign Key: Address,
  slashing_history: [{
    block_number: BlockNumber,
    reason: Enum,
    amount: Balance
  }],
  rewards_history: [{
    amount: Balance,
    authored_block: BlockNumber,
    recipients: Address[]
  }],
}
```

### App DB
```
Table(Validators): {
  Primary Key id: Address,
  profile: {
      name,
      bio,
      logo,
      controller_key,
      session_keys
  },
  commission: Balance,
  total_stake: Balance
}
```

```
Table(Nominators): {
  id,
  profile: {
      name,
      bio,
      logo,
      controller_key: Address,
      stash_key: Address
  },
  favorites: Address[],
  currently_nominating: [{
      validator: Address,
      session: BlockNumber,
      bonded: Balance,
      reward_preference: Enum 
  }],
  past_nominations: [{
      validator: Address,
      session: BlockNumber,
      bonded: Balance,
      reward_preference: Enum 
  }]
}
```
