### ISSUE TITLE
bug(nodewatcher): update types for specVersion 1032

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#101]
pseudocode
```
if 1019 <= specversion < 1032:
injectTypes(types: {
      DispatchError: 'DispatchErrorTo198',
      Keys: 'SessionKeys5'
    })

if specversion >= 1032
  inject types ( types: {
      Keys: 'SessionKeys5'
    })
```

see https://github.com/polkadot-js/api/blob/master/packages/api/src/base/typeInjector.ts#L33

**Comment by amaurymartiny** [comment]
Yeah, but don't hardcode anything (e.g. "1019", "DispatchErrorTo198") in Nomidot, just use the 2 exported functions from the link above
