### ISSUE TITLE
Speed up Nodwatcher Sync

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#111]
Seems to average around 25 writes per second, which sounds good but that's approximately how many writes per block we have at this point. (there are only 86,400 seconds in a day)...

![Screenshot 2020-01-27 at 15 29 13](https://user-images.githubusercontent.com/10432070/73182746-e1698c00-4119-11ea-9a44-3bd2a1f33b49.png)

![Screenshot 2020-01-27 at 15 36 07](https://user-images.githubusercontent.com/10432070/73183231-c5b2b580-411a-11ea-8bf9-7ca446c9fb21.png)

The good news is that memory usage seems to be growing slower as time goes on, currently hovering around 1.75GB.

While I'm tempted to upgrade our instance to speed it up, the CPU utilization is only at like 5-10%, so I guess we should figure out how to squeeze more out of the current instance as it is.

**Comment by yjkimjunior** [comment]
A pretty simple solution would be to have multiple scripts start from different blocks.

Say we have `N` scripts, and current best head `H`, we just run each script `i` from `block # ((H/N) * i)`.

Importantly, all but the last script deployment needs to know when to stop, so we avoid duplicate work. Probably just an environment variable per deployment will do.

**Comment by yjkimjunior** [comment]
at the current speed though it'll need at least 10 workers in parallel to be able to sync in a couple days.

**Comment by amaurymartiny** [comment]
I personally thinking spawning 10 workers is really overkill, and would rather understand what is actually taking so long before building the devops for 10 worksers.

So the question is: who's the bottleneck in those 25w/s:
- If the network requests between nodeWatcher and the archive node are taking 90% of that time, then maybe we should spawn an archive node in the same cluster.
- If the bottleneck is the nodeWatcher itself, maybe we should refactor the tasks. Right now we run those sequentially, but we could have easily 2-3x speedup by parallezing some tasks. E.g. define some dependency graph (e.g.: task1 needs task2 and task3, but all other tasks can run parallely).
- If the bottleneck is actually writing into Prisma, then maybe we should dig more into that direction?

Maybe we could refactor nodeWatcher to run some tasks in parallel?

**Comment by yjkimjunior** [comment]
^^ sounds a lot better than having 10 workers.

I'm not entirely sure which is the main bottleneck, but the first 2 points are probably good to have in any case. I'll test out the second solution, if not seeing much improvment then try the first as well.

**Comment by yjkimjunior** [comment]
it's as if it heard us complaining

![Screenshot 2020-01-27 at 17 26 48](https://user-images.githubusercontent.com/10432070/73193004-37463000-412a-11ea-8d30-92317e041e79.png)

**Comment by amaurymartiny** [comment]
Maybe we could run once with a lot of console.time, just to find the bottleneck

**Comment by amaurymartiny** [comment]
> it's as if it heard us complaining
> 
> ![Screenshot 2020-01-27 at 17 26 48](https://user-images.githubusercontent.com/10432070/73193004-37463000-412a-11ea-8d30-92317e041e79.png)

lol, we can close this issue

**Comment by yjkimjunior** [comment]
so console.time reveals the obvious, that awaiting queries from a node is certainly a bottleneck. I'm sure putting a node in the same cluster would help, though not sure by how much.

Dependency graph of tasks looks like this:
![Screenshot 2020-01-27 at 19 17 54](https://user-images.githubusercontent.com/10432070/73201631-bc851100-4139-11ea-8563-c4eedd7189b8.png)

Not sure that parallelizing them is so straightforward in Javascript though...

**Comment by yjkimjunior** [comment]
anyway the recent performance boost seems to be persisting, thanks google

**Comment by yjkimjunior** [comment]
luckily it's absolutely flying through now after we've done the optimizations refactor and added 1 extra cpu :)
