### ISSUE TITLE
cloudsql db: start syncing v1.5 db

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#190]
rather than upserting stuff in the existing DB our "migration" will just be to resync what we need in a new db with new schemas.

@Tbaut @niklabh if there are schemas that need to be updated, please add them soon (I will do the same for Nomidot). I think we could launch the new set of jobs by let's say next Monday (2/24)?

**Comment by Tbaut** [comment]
We have still maaany things to track. We'll start with treasury #183 
tech committee will follow, then voters for motion/referenda/proposal, then council members, then.. and so on and so on. We'll not be done before a while, so go ahead and start a sync, we'll manage.

We generally have no schema change, by that I mean breaking change and are interested in "new" data, so just adding things to the DB, starting from a couple days old before the launch of a feature. We can still run some additional jobs that just track whatever we added, I expect this to speed up the sync. But this is a case by case job we'll do.

**Comment by yjkimjunior** [comment]
ok, I don't assume things will slow down for a while, but just wanted to communicate my intention here so no one is caught off guard (and so we have a better chance of this sync completing smoothly).
