### ISSUE TITLE
Create a node watcher: Archive node -> PgSQL

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/Nomidot#20]
The idea is to have a long-living script that will do the following:
1. point to an archive node
2. take as input a config file which describes which part of the state we want to store in the DB
    - actual API of this config file to be discussed, but basic idea for now is e.g.: `api.rpc.chain.bestBlock: "pgsql.table_blocks"` or `api.derive.staking.overview: "pgsql.table_staking"`
3. Set N=1, and with PolkadotJS api query everything the config file dictates from the archive node at block N, and save it to DB.
4. Do N:=N+1, and repeat step 3. Stop when the script reaches the tip of the chain (finalized head for now, to avoid reorgs).
5. On each new block of the archive node, repeat step 3.

cc @Tbaut @niklabh

**Comment by yjkimjunior** [comment]
Ok, so we have a node-watcher now that seemingly works.

Next steps to get that hosted are:
1. Publish the node-watcher (client), psql (db), prisma (server) docker images to Google Container Registry
2. Deploy that image to a staging namespace in a Kubernetes cluster
3. 
4. Add some hooks to spin up a new DB and watcher when a PR with a `-chaindb` tag is merged to master, point the Graphql server to the new DNS once it's ready.
5. Once there is a watcher that's synced to the tip and live, publish to the production namespace
6. From there on, repeat step 4, 5 as shit goes down.

Playing around with getting this working on my personal GCP account for now. Container Registry actually let's us use docker-compose so we have less to think about.

**Comment by yjkimjunior** [comment]
Small update, instead of containerizing our db as another Pod, we'll just use CloudSQL so we don't have to deal with DNS resolution whenever Pods go down then up again with a new IP address. This should "just work." So currently its' working on my local minikube cluster, we'll see how this goes on testinstallations

**Comment by yjkimjunior** [comment]
It lives! https://console.cloud.google.com/sql/instances/kusama-etl/overview?authuser=1&project=test-installations-222013&duration=PT1H
