### ISSUE TITLE
Nominator dashboards Mega-Thread

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/Nomidot#21]
This issue tracks all nominator/validator dashboards for Kusama/Polkadot out there in the wild.

`@parity.io`-accessible gdoc: https://docs.google.com/spreadsheets/d/1qKZPMdtz11Ivw3-jaGFOx5yAwoxKwWNaTHNgdocpkTE/edit#gid=0

If you know of some nominator dashboards (or are building one), please advertize below.

**Comment by amaurymartiny** [comment]
[reserved]

**Comment by yjkimjunior** [comment]
### Polkawallet
* Website: https://polkawallet.io
* Github: https://github.com/polkawallet-io/polkawallet-RN

### Lunie (Announced but pre-Development)
* https://twitter.com/luniehq
* https://medium.com/luniehq/introducing-the-new-lunie-8c015153ef3

**Comment by yjkimjunior** [comment]
moved to Notion https://www.notion.so/Nomidot-WIP-name-18e54b1518b94ea992e7a886e20528d1
