### ISSUE TITLE
There shouldn't be unmaintained yarn.locks in this package

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/Nomidot#244]
@Tbaut  updated polkadot/api in https://github.com/paritytech/Nomidot/pull/242, and it correctly updated the root yarn.lock.

However, there are 2 other yarn locks in this repo, and even after Tbaut's update, they are still at `@polkadot/api@1.6.x`. Maybe that's the cause of #233?

2 solutions:
1. remove those 2 other yarn locks, and only use the root yarn.lock. We would need to either change the WORKDIR of some Dockerfile [e.g. this one](https://github.com/paritytech/Nomidot/blob/master/back/node_watcher/Dockerfile), so that they can access the root yarn.lock, or create a script that temporarily copies the root yarn.lock into the WORKDIR then deletes it

2. Remove back/node_watcher and back/server from yarn workspace. They will have their own yarn.lock & node_modules. If we update e.g. `@polkadot/api`, we would then need to update in the root `package.json`, and also in each of those independent package's `package.json`.

**Comment by Tbaut** [comment]
@yjkimjunior the solution 1 was implemented in #245

Please close this if you're ok with that, or let us know if you think the solution 2 should rather be implemented. Noone has a strong opinion on that right now.

Unfortunately, this does not seem to solve #233

**Comment by yjkimjunior** [comment]
i personally definitely prefer solution 1

**Comment by Tbaut** [comment]
cool, closing since we did that.
