### ISSUE TITLE
Retry when error in node_watcher

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/Nomidot#253]
When node_watcher errors, we had multiple strategies:

**Before**:

```ts
  api.once('disconnected', () => {
    api = new Api();
  });

  while(true) {
    // do stuff on each block
    api.*.*.*
  }
```

I think this version is just bugged. Too many race conditions, shared references...

**Now**:

```ts
  api.once('disconnected', () => {
     process.exit(1);
  });
```

Works, but not clean, as Gabriel pointed out.

**Ideas**:

```diff
// Incrementor should not take an api object anymore

- async function incrementor(
-   api: ApiPromise,
-   provider: WsProvider,
-   tasks: NomidotTask[]
- ): Promise<void> {

+ async function incrementor(
+   tasks: NomidotTask[]
+ ): Promise<void> {

// Remove this
-   api.once('disconnected', () => {
-     process.exit(1);
-  });

// Remove this block of code
// https://github.com/paritytech/Nomidot/blob/dfdf873cdb1e902f01bc392577f72a08c0222dc9/back/node_watcher/src/nodeWatcher.ts#L67-L72
// Refactor it so that it can code inside the while loop, because that's the only place where there's an api object

// The only variable that stays out of the loop is `blockIndex`
let blockIndex = parseInt(process.env.START_FROM || '0');

while (true) {
  // All the code goes into a retry function. It takes a function returning a Promise, if the Promise fails, it retries. We can use a library for this, the lib will handle exp backoff, retry count etc.
  // This `retry` function also handles creation of the api object. At the beginning, it will create a new Api(). If it catches an error, then it first destroys the old api, then creates a new one, then passes the new one to the inner function
+  retry(async (api: ApiPromise)=> {

+     api.once('disconnected', () => {
+       throw new Error(); // will be caught by the `retry`
+    });

      // do all the tasks
+  });
}
```

Just throwing some ideas, happy to revisit.

Caveats:
- if at block N, node_watcher does 7/10 tasks, and api gets disconnected at the 8th task, the the `retry` function will start again at the 1st task, possibly creating duplicate content in the DB. That's not ideal... To mitigate this, we could:
  - silent prisma duplication errors
  - on error on retry, revert DB writes (cleaner, but harder to do)

**Comment by amaurymartiny** [comment]
**Another idea:**

Similar to the previous one, but instead of having one big `retry` at the beginning inside the loop, have multiple smaller ones.

So everywhere where we use api, we would need to replace it with `retry`. E.g.:

```diff
- const result = await task.read(blockHash, cached, api);
+ const result = await retry((api) => task.read(blockHash, cached, api))
```

**Comment by Tbaut** [comment]
> if at block N, node_watcher does 7/10 tasks, and api gets disconnected at the 8th task, the the retry function will start again at the 1st task, possibly creating duplicate content in the DB. That's not ideal... To mitigate this, we could:
        silent prisma duplication errors
        on error on retry, revert DB writes (cleaner, but harder to do)

Right now we actually silence the prisma errors, because those happen quite a lot depending on what we do. This is probably not the best, but in you scenario, we'll have 7 retry errors, and it'll successfully finish the 3 remaining.

**Comment by niklabh** [comment]
One idea i had was to use https://github.com/Automattic/kue Async task queue backed by redis. You can process tasks one by one and remove when acknowledged. Push all the block number not processed in kue and process one by one. Listen for new blocks from chain and push it on kue

**Comment by Tbaut** [comment]
done in #254
