### ISSUE TITLE
Onboarding with extension

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#3]
* List all accounts from extension
* ask user to select one as stash and one as controller
* Check if account selected as stash has been tagged as stash, if conflict, notify the user, else, save it to our backend profiles table
* Once Stash and Controller have been established, redirect to the @validators page.

**Comment by yjkimjunior** [comment]
@amaurymartiny, with nomidot's context provider, we are using the keyring, but since we're going to be defaulting to extension now, I want to remove that entirely. If people want to use a context with keyring they can use `react-api`. What do you think?

**Comment by amaurymartiny** [comment]
Yes, agreed on removing `keyring` altogether. So what I would do is actually have the following contexts:
- `AccountsContext`: Manages all accounts. Query the extension from this context.
- `ApiContext`: Creates an API object. (basically the old AppContext, minus keyring)
- `TxQueueContext` & `AlertsContext`: they stay the same
- `StakingContext`: We could keep it for now, though ideally I don't think a context is needed.

**Comment by amaurymartiny** [comment]
And we can keep keyring in the light-ui. If you do the rename `AppContext` -> `ApiContext` in your PR (and publish the package), then I'll probably go ahead and create a `KeyringContext` in light-ui.

**Comment by amaurymartiny** [comment]
Also, I think we should put ContextGate in `gastby`. The `context` package should just expose React contexts, and let the user pick the ones he/she wants.
